import { getSvg } from "src/app/svg/svgIcon";
import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/admin/dashboard/main",
    title: "Home",
    icon: getSvg[0]?.home,
    iconhover:getSvg[0]?.home1,
    isHover:false,
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

  {
    path: "/leave/leave",
    title: "ME",
    icon: getSvg[0]?.user,
    iconhover:getSvg[0]?.user1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "leave/leave",
        title :"LEAVE",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "leave/reimbursement",
        title :"REIMBURSEMENT",
        icon: getSvg[0]?.user,
      iconhover:getSvg[0]?.user1,
      isHover:false,
      class: "menu-toggle",
      groupTitle: false,
      badge: "",
      badgeClass: "",
      role: ["Admin"],
      submenu:[]
      },
      {
         path: "leave/book-my-travel",
        title :"BOOK MY TRAVEL",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "leave/attendance",
        title :"ATTENDANCE",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "leave/wfh",
        title :"WORK FROM HOME",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "leave/jobrequest",
        title :"JOB REQUEST",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]


      },
      {
         path: "leave/goal",
        title :"GOAL" ,
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      }
  ],

  },

  {
    path: "/ticket/ticket-dashboard",
    title: "Help Desk",
    icon: getSvg[0]?.helpdesk,
    iconhover:getSvg[0]?.helpdesk1,
    isHover:false,
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
         path: "ticket/ticket-dashboard",
         title :"TICKET DASHBOARD",
         icon: getSvg[0]?.user,
         iconhover:getSvg[0]?.user1,
         isHover:false,
         class: "menu-toggle",
         groupTitle: false,
         badge: "",
         badgeClass: "",
         role: ["Admin"],
         submenu:[]
      },
      {
         path: "ticket/ticket-category",
         title :"TICKET CATEGORY",
         icon: getSvg[0]?.user,
         iconhover:getSvg[0]?.user1,
         isHover:false,
         class: "menu-toggle",
         groupTitle: false,
         badge: "",
         badgeClass: "",
         role: ["Admin"],
         submenu:[]
      },
      {
         path: "ticket/ticket-raised",
         title :"TICKET RAISED",
         icon: getSvg[0]?.user,
         iconhover:getSvg[0]?.user1,
         isHover:false,
         class: "menu-toggle",
         groupTitle: false,
         badge: "",
         badgeClass: "",
         role: ["Admin"],
         submenu:[]
      },
      {
         path: "ticket/ticket-received",
         title :"TICKET RECEIVED",
         icon: getSvg[0]?.user,
         iconhover:getSvg[0]?.user1,
         isHover:false,
         class: "menu-toggle",
         groupTitle: false,
         badge: "",
         badgeClass: "",
         role: ["Admin"],
         submenu:[]
      },],

  },
  {
    path: "",
    title: "Project",
    icon: getSvg[0]?.project,
    iconhover:getSvg[0]?.project1,
    isHover:false,
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],

  },

  {
    path: "/notification/notification",
    title: "Notification",
    icon: getSvg[0]?.notification,
    iconhover:getSvg[0]?.notification1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "notification/notification",
        title :"NOTIFICATIONS",
        icon: getSvg[0]?.notification,
        iconhover:getSvg[0]?.notification1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
    ],


  },
  {
    path: "/efms/efms",
    title: "EFMS",
    icon: getSvg[0]?.Efms,
    iconhover:getSvg[0]?.Efms1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "efms/efms",
        title :"FEEDBACK CATEGORY",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "efms/teams",
        title :"TEAMS",
        icon: getSvg[0]?.user,
      iconhover:getSvg[0]?.user1,
      isHover:false,
      class: "menu-toggle",
      groupTitle: false,
      badge: "",
      badgeClass: "",
      role: ["Admin"],
      submenu:[]
      },
      {
         path: "efms/feedback",
        title :"GIVE FEEDBACK",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "efms/anonymous",
        title :"ANONYMOUS",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "efms/reportfeedback",
        title :"FEEDBACK REPORT",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "efms/endoresement",
        title :"ENDORSEMENT",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "efms/skills",
        title :"SKILLS",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]


      },
      {
         path: "efms/reportskills",
        title :"SKILLS REQUEST" ,
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
         path: "efms/goal-management",
        title :"GOAL MANAGEMENT" ,
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      }
  ],


  },
  {
    path: "/organization/organization",
    title: "Organization",
    icon: getSvg[0]?.organization,
    iconhover:getSvg[0]?.organization1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "organization/organization",
        title :"ORGANIZATION",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "organization/orgtree",
        title :"ORGANIZATION TREE",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "organization/leavedashboard",
        title :"LEAVE DASHBOARD",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "organization/reimbursement_dashboard",
        title :"REIMBURSEMENT DASHBOARD",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "organization/department",
        title :"DEPARTMENT",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
      {
        path: "organization/designation",
        title :"DESIGNATION",
        icon: getSvg[0]?.user,
        iconhover:getSvg[0]?.user1,
        isHover:false,
        class: "menu-toggle",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu:[]
      },
    ],


  },
  {
    path: "",
    title: "CRM",
    icon: getSvg[0]?.emossy,
    iconhover:getSvg[0]?.emossy1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Our Employee",
    icon: getSvg[0]?.ourEmployee,
    iconhover:getSvg[0]?.ourEmployee1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Approval",
    icon: getSvg[0]?.approval,
    iconhover: getSvg[0]?.approval1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Recruitment",
    icon: getSvg[0]?.recruitment,
    iconhover:getSvg[0]?.recruitment1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Asset Master",
    icon: getSvg[0]?.assetmaster,
    iconhover: getSvg[0]?.assetmaster1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Pay Roll",
    icon: getSvg[0]?.payroll,
    iconhover:getSvg[0]?.payroll1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Career",
    icon: getSvg[0]?.career,
    iconhover:getSvg[0]?.career1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Performance",
    icon: getSvg[0]?.performance,
    iconhover:getSvg[0]?.performance1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Our Intranet",
    icon: getSvg[0]?.ouritranet,
    iconhover:getSvg[0]?.ouritranet1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "FAQ",
    icon: getSvg[0]?.faq,
    iconhover:getSvg[0]?.faq1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Permission",
    icon: getSvg[0]?.permission,
    iconhover:getSvg[0]?.permission1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },
  {
    path: "",
    title: "Client Masster",
    icon: getSvg[0]?.clientmaster,
    iconhover:getSvg[0]?.clientmaster1,
    isHover:false,
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],


  },];

